language: python
sudo: false
addons:
  apt:
    packages:
    - libssl-dev
    - libdb-dev
cache:
  pip: true
  directories:
  - eggs
  - downloads
  - openldap
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.1
  - PLONE_VERSION=5.2
python:
  - "2.7"
matrix:
  fast_finish: true
install:
  - pip install -r requirements-${PLONE_VERSION}.x.txt
  - buildout -Nc buildout-${PLONE_VERSION}.x.cfg buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - buildout -Nc buildout-${PLONE_VERSION}.x.cfg buildout:download-cache=downloads code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls